
                      ## LECCION 1
                # CONTROL DE CAMBIOS EN R

# PERMITE RECONOCER QUE MODIFICACIONES SE HAN RELIZADO A UN CODIGO, CUANDO Y QUIEN LAS REALIZO
# AL REALIZAR UNA MODIFICACIÓN EL CONTROL DE CAMBIOS GUARDA UNA CAPTURA DE LA VERSIÓN ORIGINAL DEL CODIGO
# PEMITIENDO REGRESAR A LA VERSION ORIGINAL EN CASO DE SER NECESARIO

# EXISTEN DISTINTOS SISTEMAS QUE PERMITEN REGISTRAR EL CONTROL DE CAMBIOS EN UN CODIGO.
# UNO DE ESTOS SISTEMAS ES GIT.

# VENTAJAS DE UTILIZAR EL CONTROL DE CAMBIOS

# 1.PERMITE INCLUIR EN UN SOLO ARCHIVO TODAS LAS REVISIONES, ELIMINANDO LA NECESIDAD DE CONTAR CON MULTIPLES VERSIONES DE UN DOCUMENTO.
# 2.ELIMINA LOS ERRORES ASOCIADOS A LA UTILIZACION DE UNA VERSION EQUIVOCADA DEL DOCUMENTO.
# 3.PERMITE QUE MULTIPLES PERSONAS TRABAJEN EN UN MISMO DOCUMENT, UNIENDO LAS VERSIONES DEL DOCUMENTO ELABORADAS POR CADA PERSONA EN UN SOLO DOCUMENTO.
# 4.PERMITE GUARDAR COPIAS CON LA VERSION MAS ACTUALIZADA DE MANERA LOCAL, PARAR SU MODIFICACION Y POSTERIOR ENVIO A UN REPOSITORIO COMUN.
# 5.GUARDA UN REGISTRO DE TODOS LOS CAMBIOS REALIZADOS A UN DOCUMENTO, PERMITIENDO REGRESAR A VERSIONES ANTERIORES EN CASO DE ERRORES O CORRECCIONES.

#GIT VS GITHUB

#GIT ES UN SOFTWARE LOCAL ENCARGADO DE REGISTRAR EL CONTROL DE CAMBIOS.
#GITHUB ES UN REPOSITORIO EN LINEA EN EL CUAL SE GUARDAN LOS ARCHIVOS Y LOS CAMBIOS REALIZADOS EN ESTOS ARCHIVOS.

# VOCABULARIO DE GITHUB

#REPOSITORY: ES LA CARPETA EN LA CUAL SE ALMACENAN LOS ARCHIVOS DE TRABAJO Y EL HISTORIAL DE CAMBIOS.
#COMMIT: ES EL REGISTRO DE CADA CAMBIO REALIZADO AL ARCHIVO. AL REALIZAR CAMBIOS A UN ARCHIVO SE DEBE AGREGAR UNA NOTA QUE DESCRIBA LOS CAMBIOS REALIZADOS Y SU FINALIDAD.
#PUSH: ENVIA AL REPOSOTORIO LOS CAMBIOS REALIZADOS EN EL ARCHIVO.
#PULL: DESCARGA DEL REPOSITORIO EL ARCHIVO MAS RECIENTE
#STAGING: EN CASO DE CONTAR CON MAS DE UNA VERSION MODIFICADA DEL ARCHIVO, PARA LA CUALES SE QUIERE INDICAR EXPLICITAMENTE LOS CAMBIOS DE UNA A OTRA VERSION SE DEBEN SUBIR LOS ARCHIVOS EN FORMA ESCALONADA ACOMPAÑADOS DE LAS DESCRIPCIÓN CORRESPONDIENTE.
#BRANCH: SE DENOMINA DE ESTA FORMA A LA SITUACION EN LA CUAL SE CUENTA CON DOS COPIAS DE UN ARCHIVO PARA TRABAJAR DE FORMA SIMULTANEA FUERA DEL REPOSITORIO.
#MERGE: ES LA ACCION DE COMBINAR DOS O MAS VERSIONES DE UN ARCHIVO
#CONFLICT: SE PRESENTA CUANDO DOS O MAS USUARIOS REALIZAN MODIFICACIONES A UN ARCHIVO AL MISMO TIEMPO. EN ESTA SITUACION GIT ES INCAPAZ DE IDENTIFICAR EL ORDEN PARA UNIRLOS POR LO CUAL SE ACTIVA LA OPCION DE UNION MANUAL.
#CLONE: ACCION POR LA CUAL SE REALIZA UNA COPIA DE UN REPOSITORIO.
#FORK: PERMITE GUARDAR UNA COPIA PERSONAL DE UN REPOSITORIO EN LA CUAL LOS CAMBIOS REALIZADOS A UN ARCHIVO NO SE REFLEJAN EN EL REPOSITORIO COMPARTIDO. 

# UTILIZANDO REPOSITORIOS

#SE ACONSEJA UTILIZAR UN REPOSITORIO PARA CADA PROYECTO E INCLUIR UN ARCHIVO DE TEXTO CON UNA DESCRIPCION BREVE DEL PROYECTO

# PASOS PARA TRABAJAR CON CONTROL DE CAMBIOS

# 1.CREAR UN ARCHIVO.
# 2.GUARDAR EL ARCHIVO(EN EL DISCO LOCAL).
# 3.REGISTRAR LOS CAMBIOS (COMMIT)
# 4.GUARDAR EL ARCHIVO EN EL REPOSITORIO DE GITHUB (PULL).

###############################################################################################################################################################################################################################################################################

                        ## LECCION 2
                  # VINCULAR RSTUDIO Y GITHUB

# PASOS PARA VINCULAR RSTUDIO Y GITH:

#1.EN RSTUDIO IR A TOOLS->GLOBAL OPTIONS->GIT/SVN
#2.VERIFICAR QUE LA DIRECCION EN QUE SE ENCUENTRA RSTUDIO CONCUERDE CON LA SEÑALADA EN LA VENTANA DE OPCIONES Y SELECCIONAR ACEPTAR

#PASOS PARA VINCULAR RSTUDIO Y GITHUB
#1.EN RSTUDIO IR A TOOLS->GLOBAL OPTIONS->GIT/SVN
#2.SELECCIONAR LA OPCION "CREATE RSA KEY" Y SELECCIONAR CERRAR AL FINALIZAR.
#3.SELECCIONAR LA OPCION "VIEW PUBLIC KEY" Y COPIAR EL CODIGO DE ESTA VENTANA, UNA VEZ COPIADO CERRAR LA VENTANA.
#4.INICIAR SESION EN GITHUB->IR A "SETTINGS"-> "SSH AND GPG KEYS"-> "NEW SSH KEY"-> PEGAR EL CODIGO COPIADO PREVIAMENTE, ASIGNAR UN NOMBRE Y ACEPTAR

#AL COMPLETAR LOS PASOS ANTERIORES GIT/GITHUB Y RSTUDIO ESTARÁN VINCULADOS.

#CREAR UN REPOSITORIO Y EDITARLO EN RSTUDIO

#PASOS PARA CREAR EL REPOSITORIO:

#1.EN GITHUB-> SELECCIONAR NUEVO REPOSITORIO-> ASIGNAR UN NOMBRE Y DESCRIPCION AL NUEVO REPOSITORIO-> SELECCIONAR CREAR Y COPIAR LA DIRECCION DEL REPOSITORIO.
#2.EN RSTUDIO-> "FILE"->"NEW PROJECT"-> "VERSION CONTROL(TERCERA OPCION)"->SELECCIONAR GIT->PEGAR LA DIRECCION COPIADA PREVIAMENTE Y ELEGIR LA CARPETA EN QUE SE GUARDARA->SELECCIONAR "CREATE PROJECT".
#3.SE ABRIRA UN NUEVO PROYECTO Y UNA NUEVA SESION.
#4.CREAR UN NUEVO SCRIPT Y PEGAR EL SIGUIENTE CODIGO:

print("This file was created within Rstudio")

print("And now it lives on GitHub")

#5.GUARDAR EL ARCHIVO.
#6.EN LA VENTANA SUPERIOR DERECHA BUSCAR LA OPCION "GIT"->SELECCIONAR LA CASILLA "STAGED" A UN COSTADO DEL SCRIPT CREADO->SELECCIONAR "COMMIT"->CERRAR LA VENTANA
#7.A CONTINUACION SE DEBE ENVIAR EL ARCHIVO ACTUALIZADO CON CONTROL DE CAMBIOS AL REPOSITORIO DE GITHUB->SELECCIONAR "PUSH"-> EN GITHUB VERIFICAR QUE EL ARCHIVO SE HAYA ACTUALIZADO.

###############################################################################################################################################################################################################################################################################

                            ## LECCION 3
              # VINCULAR PROYECTOS EXISTENTES A GITHUB

#PASOS PARA VINCULAR UN PROYECTO EXISTENTE A GITHUB

#1.SELECCIONAR "FILE"-> "NEW PROJECT"-> "NEW DIRECTORY"-> "NEW PROJECT", NOMBRAR EL PROYECTO-> NO MARCAR LA CASILLA "CREATE A GIT REPOSITORY".
#2.ABRIR GITBASH Y NAVEGAR EN EL DIRECTORIO HASTA ENCONTRAR LA CARPETA QUE CONTIENE EL ARCHIVO UTILIZANDO LOS SIGUIENTES COMANDOS:
# pwd -> cd /Users/scorp\OneDrive\ESCRITORIO/RES

##NOTAS SOBRE GITBASH

## A)PWD: PRINT WORKING DIRECTORY 
## B)CD: CHANGE DIRECTORY
##    B1)TRUCO: PARA FIJAR RUTAS DE MANERA SENCILLA ESCRIBIR EL COMANDO CD, POSTERIORMENTE ESCRIBIR LAS PRIMERAS LETRAS DEL NOMBRE DE LA CARPETA O ARCHIVO QUE REFERIRA LA RUTA Y APRETAR TAB.
##        DE ESTA FORMA GIT AUTOCOMPLETA LA RUTA SIN ERRORES.
##    B2)TRUCO: PARA REGRESAR UN NIVEL EN LA RUTA INGRESAR EL COMANDO CD ..
##    B3)TRUCO: PARA REGRESAR DOS NIVELES EN LA RUTA INGRESAR EL COMANDO CD ../..
##    B4)TRUCO: PARA BORRAR LA DIRECCION A LA DERECHA DEL CURSOR OPRIMIR CTRL+K
##    B5)TRUCO: PARA BORRAR LA DIRECCION A LA IZQUIERDA DEL CURSOR OPRIMIR CTRL+U
## C)MKDIR(NAME): MAKE DIRECTORY
## D)LS:LISTA LOS ARCHIVOS Y CARPETAS EN ESA DIRECCION
## E)LS -L:LISTA LOS ARCHIVOS Y CARPETAS EN ESA DIRECCION (ORDENADO EN COLUMNAS)
## F)LS -L (LETRA)*:LISTA LOS ARCHIVOS Y CARPETAS EN ESA DIRECCION QUE INICIAN CON ESA LETRA 
## G)LS -A (LETRA)*:LISTA TODOS LOS ARCHIVOS Y CARPETAS EN ESA DIRECCION INCLUSO ARCHIVOS OCULTOS
## H)CTRL+L: LIMPIA LA PANTALLA, PERO CONSERVA EL COMANDO QUE SE ESTE ESCRIBIENDO EN ESE MOMENTO
## I)CLEAR: LIMPIA LA PANTALLA POR COMPLETO
## J)PARA INDICAR UNA RUTA DE MANERA RAPIDA: ABRIR EL EXPLORADOR DE ARCHIVOS->SELECCIONAR LA CARPETA DE TRABAJO DESEADA CON CLICK DERECHO Y ELEGIR LA OPCION "GIT BASH HERE"

#3.UNA VEZ EN EL DIRECTORIO CORRECTO INGRESAR LOS COMANDOS:
##    GIT INIT: PERMITE INICIALIZAR ESTE DIRECTORIO EN EL REPOSITORIO
##    GIT ADD .: AGREGA LOS ARCHIVOS DE LA RUTA LOCAL AL REPOSITORIO
##    GIT COMMIT -M "INITIAL COMMIT": REGISTRA LOS CAMBIOS REALIZADOS

## LOS PASOS ANTERIORES HAN PERMITIDO CREAR UN PROYECTO DE RSTUDIO Y AHORA DEBE LIGARSE A LA VERSION EN CONTROL DE CAMBIOS

#4.IR A GITHUB Y CREAR UN NUEVO REPOSITORIO(DEBE TENER EL MISMO NOMBRE QUE EL PROYECTO DE R CREADO PREVIAMENTE Y NO SE DEBE INICIAR EL ARCHIVO README, .GITIGNORE O LICENSE)
#5.COPIAR EL CODIGO INCLUIDO EN LA SECCION TITULADA "…or push an existing repository from the command line" Y PEGARLO EN GIT BASH

## REALIZADOS LOS PASOS ANTERIORES YA SE SINCRONIZO EL NUEVO REPOSITORIO CON EL PROYECTO, POR LO QUE AL ABRIR DE NUEVA CUENTA EL PROYECTO YA ESTARA HABILITADA LA OPCION DE GIT EN
## LA VENTANA SUPERIOR DERECHA.

                  ## CLONAR UN REPOSITORIO EXISTENTE EN GITHUB

#PASOS PARA CREAR EL REPOSITORIO:

#1.EN RSTUDIO-> "FILE"->"NEW PROJECT"-> "VERSION CONTROL(TERCERA OPCION)"->SELECCIONAR GIT->PEGAR LA DIRECCION DEL REPOSITORIO QUE SE DESEA CLONAR Y ELEGIR LA CARPETA EN QUE SE GUARDARA->SELECCIONAR "CREATE PROJECT".
#2.SE ABRIRA UN NUEVO PROYECTO Y UNA NUEVA SESION.
#3.CREAR UN NUEVO SCRIPT Y PEGAR EL SIGUIENTE CODIGO:

print("This file was created within Rstudio")

print("And now it lives on GitHub")

#5.GUARDAR EL ARCHIVO.
#6.EN LA VENTANA SUPERIOR DERECHA BUSCAR LA OPCION "GIT"->SELECCIONAR LA CASILLA "STAGED" A UN COSTADO DEL SCRIPT CREADO->SELECCIONAR "COMMIT"->CERRAR LA VENTANA
#7.A CONTINUACION SE DEBE ENVIAR EL ARCHIVO ACTUALIZADO CON CONTROL DE CAMBIOS AL REPOSITORIO DE GITHUB->SELECCIONAR "PUSH"-> EN GITHUB VERIFICAR QUE EL ARCHIVO SE HAYA ACTUALIZADO.

###############################################################################################################################################################################################################################################################################

                                ## LECCION 4
                                ## R MARKDOWN

#¿QUE ES R MARKDOWN?
#ES UNA FORMA DE CREAR DOCUMENTOS QUE COMBINAN TEXTO TEXTO Y CODIGO.
#ESTOS DOCUMENTOS PUEDEN SER CONVERITDOS A FORMATO HTML, PDF, DOCUMENTOS DE WORD O DIAPOSITIVAS.ESTA HERRAMIENTA PERMITE LA ELABORACION DE DOCUMENTOS QUE INTEGRAN TEXTO, PLANTEAMIENTO DE HIPOTESIS,
#EL CODIGO CON LAS PRUEBAS DE CONTRASTE DE HIPOTESIS Y LAS CONCLUSIONES DE LA INVESTIGACION, FACILITANDO SU DIFUSION Y UTILIZACION POR DIVERSOS USUARIOS.
#OTRO DE LOS BENEFICIOS DE R MARKDOWN S QUE INTEGRA LAS FUNCIONALIDADES DE TRABAJAR EN CONTROL DE CAMBIOS, PERMITIENDO IDENTIFICAR PUNTUALMENTE LAS MODIFICACIONES REALIZADAS A UN DOCUMENTO.

#VERIFICAR VERSION INSTALADA DE R
R.version.string
#ACTUALIZAR VERSION DE R
install.packages("installr")
#LIBRERIA
library(installr)
#ACTUALIZA R
updateR()

#INSTALAR R MARKDOWN
install.packages("rmarkdown")
install.packages("caTools")

#LLAMAR LIBRERIA
library(rmarkdown)

#CREAR UN ARCHIVO DE R MARKDOWN
#IR A FILE->NEW FILE->R MARKDOWN->SELECCIONAR FORMATO AL CUAL SE DESEA CONVERTIR EL DOCUMENTO->SELECCIONAR ACEPTAR.
#EL ARCHIVO DE R MARKDOWN SE COMPONE DE LOS SIGUIENTES ELEMENTOS:
#1.ENCABEZADO:EN ESTA SECCION SE COLOCA EL TITULO DEL DOCUMENTO, AUTOR, FECHA Y EL FORMATO DEL DOCUMENTO A CREAR.
#2.SECCION DE TEXTO:EN ESTA SECCION SE DEBE INCLUIR EL CONTENIDO DEL ARCHIVO A CREA.
#3.SECCION DE CODIGO:EN ESTA SECCION SE COLOCA EL CODIGO ADECUADO AL TEMA DEL DOCUMENTO, LOS RESULTADOS DE ESTE CÓDIGO SERÁN EXPORTADOS E INTEGRADOS AL FORMATO DE DOCUMENTO INDICADO.
#PARA EXPORTAR EL DOCUMENTO, UNA VEZ CONCLUIDA SU EDICION SELECCIONAR->"KNIT" EN LA BARRA DE HERRAMIENTAS

#APLICAR FORMATO AL DOCUMENTO DE R MARKDOWN
#NEGRITAS:INCLUIR DOS ASTERISCOS (**BOLD**)
#CURSIVAS:INCLUIR UN ASTERISCO (**ITALICS**)
#AGREGAR ENCABEZADOS
#PARA AGREGAR ENCABEZADOS COLOCAR EL SIMBOLO DE NUMERO(#ENCABEZADO)
#SI SE AGREGAN MAS SIMBOLOS DE NUMERO(#) SE ORDENA QUE ESE ENCABEZADO TENGA UN NIVEL DISTINTO, A MAYOR CANTIDAD DE SIMBOLOS DE NUMERO MENOR TAMAÑO DE LETRA DEL ENCABEZADO
#AGREGAR LINEA DE CODIGO AL DOCUMENTO
#SELECCIONAR CTRL+ALT+I PARA INSERTAR UNA NUEVA SECCION DE CODIGO AL DOCUMENTO.
#PARA OBTENER UNA VISTA PREVIA DE UNA CADENA DE CODIGO SELECCIONAR CNTL+SHIFT+ENTER SOBRE LA CADENA QUE SE DESEA PREVISUALIZAR, O SELECCIONAR LA FLECHA VERDE EN LA PARTE SUPERIOR DE LA BARRA DE TAREAS
#PARA CREAR VIÑETAS AGREGAR UN GUION SIMPLE (-) SEGUIDO DE UN ESPACIO A CADA CATEGORIA. ES MUY IMPORTANTE QUE AL FINAL DE CADA VIÑETA SE DEJEN DOS EXPACIOS, DE LO CONTRARIO R TENDRA ERRORES EN LOS ESPACIOS

###############################################################################################################################################################################################################################################################################

                                ## LECCION 5
                  ## CATEGORIAS DEL ANALISIS DE DATOS

#EL ANALISIS DE DATOS PUEDE DIVIDIRSE EN SEIS CATEGORIAS PRINCIPALES:
# 1.DESCRIPTIVO
  #EL OBJETIVO DE ESTE TIPO DE ANALISIS CONSISTE EN PRESENTAR UN RESUMEN DE UN CONJUNTO DE DATOS. PARA LOGRAR LO ANTERIOR UTILIZA MEDIDAS DE TENDENCIA CENTRAL O DE DISPERSION.
  #ES IMPORTANTE MENCIONAR QUE ESTE ANALISIS NO IMPLICA LA INFERENCIA DE VALORES POBLACIONALES O LA ELABORACION DE CONCLUSIONES CON LA INFORMACION EXTRAIDA DEL CONJUNTO DE DATOS.

# 2.EXPLORATORIO
  #EL OBJETIVO DE ESTE TIPO DE ANALISIS CONSISTE EN EXAMINAR O EXPLORAR EL CONJUNTO DE DATOS PARA ENCONTRAR RELACIONES QUE PREVIAMENTE NO HABIAN SIDO SEÑALADAS.
  #ESTE TIPO DE ANALISIS SE ENFOCA EN EXPLORAR COMO DISTINTAS MEDICIONES PUEDEN RELACIONARSE CON OTRAS, SIN EMBARGO, NO CONFIRMA QUE ESTAS RELACIONES IMPLIQUEN CAUSALIDAD.
  #PERMITE IDENTIFICAR RELACIONES ENTRE VARIABLES PERO NO RELACIONES CAUSALES
  #DEBIDO A QUE ESTE TIPO DE ANALISIS SE ENFOCA EN LA CORRELACION ENTRE GRUPOS DE VARIABLES SE DEBE SER CUIDADOSO Y NO TOMAR LOS RESULTADOS OBTENIDOS COMO VERDADES UNIVERSALES,YA QUE ES CONOCIDO QUE LA CORRELACION DE DOS O MAS VARIABLES NO IMPLICA CAUSALIDAD

# 3.INFERENCIAL
  #EL OBJETIVO DE ESTE TIPO DE ANALISIS CONSISTE EN REALIZAR INFERENCIAS SOBRE PARAMETROS POBLACIONALES A PARTIR DE DATOS MUESTRALES
  #SE APOYA DE TECNICAS ESTADISTICAS PARA LA CREACION DE MODELOS QUE PERMITAN REALIZAR INFERENCIAS
  #PERMITE CONOCER EL GRADO DE INCERTIDUMBRE AL CUAL SE ENFRENTAN LAS INFERENCIAS REALIZADAS
  #UTILIZA INFORMACION MUESTRAL COMO INSUMO BASICO
  #LA PRECISION DE LAS INFERENCIAS REALIZADAS DEPENDE DE LA CALIDAD DE LOS DATOS UTILIZADOS COMO INSUMOS

# 4.PREDICTIVO
  #EL OBJETIVO DE ESTE TIPO DE ANALISIS CONSISTE EN PREDECIR EL COMPORTAMIENTO FUTURO DE UNA O MAS VARIABLES UTILIZANDO LA INFORMACION DE SUS VALORES PASADOS Y ACTUALES
  #PERMITE CONOCER EL GRADO DE INCERTIDUMBRE AL CUAL SE ENFRENTAN LAS PREDICCIONES REALIZADAS
  #UTILIZA INFORMACION MUESTRAL COMO INSUMO BASICO
  #LA PRECISION DE LAS PREDICCIONES REALIZADAS DEPENDE DE LA CALIDAD DE LOS DATOS UTILIZADOS COMO INSUMOS
  #ESTE TIPO DE ANALISIS TAMPOCO SE ENFOCA EN DESCRIBIR LAS RELACIONES CAUSALES ENTRE LOS DATOS
  
# 5.CAUSAL
  #EL OBJETIVO DE ESTE TIPO DE ANALISIS CONSISTE EN ANALIZAR E IDENTIFICAR LA EXISTENCIA DE RELACIONES CAUSALES ENTRE UN CONJUNTO DE DATOS
  #SE ENFOCA EN ANALIZAR EL COMPORTAMIENTO DE UNA VARIABLE AL MANIPULAR UNA O MAS VARIABLES
  #ES UN TIPO DE ANALISIS COMPLICADO CUYOS RESULTADOS DEPENDEN AMPLIAMENTE DE LOS DATOS UTILIZADOS, LAS RELACIONES ANALIZADAS Y LOS SUPUESTOS EN LOS QUE SE FUNDAMENTA EL ANALISIS.
  #TRABAJA CON DATOS AGREGADOS POR LO CUAL LAS CONCLUSIONES EXTRAIDAS PUEDEN NO SE APLICABLES A CIERTOS SUBMUESTRAS DE LA POBLACION

# 6.MECANISTICO
  #SE ENFOCA EN ANALIZAR LOS CAMBIOS EXACTOS EXPERIMENTADOS POR UNA VARIABLE AL REALIZAR UN CAMBIO EXACTO EN OTRA VARIABLE.
  #TRABAJA CON DATOS EXPERIMENTALES
  #ES APLICADO PRINCIPALMENTE EN CIENCIAS EXACTAS
  #EMPLEA TECNICAS DE MODELACION DETERMINISTA
  #AL CONTROLAR LAS VARIABLES QUE GENERAN LOS DATOS SE INCREMENTA LA CALIDAD DE LOS DATOS OBTENIDOS
  #EL "UNICO" INCONVENIENTE AL QUE SE ENFRENTA ES LA LOS ERRORES DE MEDICION EN LOS DATOS

###############################################################################################################################################################################################################################################################################

                                ## LECCION 6
                            ## DISEÑO EXPERIMENTAL

#EL DISEÑO EXPERIMENTAL CONSISTE EN ORGANIZAR UN PROCEDIMIENTO A TRAVES DEL CUAL SE OBTENGAN LOS DATOS NECESARIOS PARA RESPONDER UNA PREGUNTA DE CIENCIA DE DATOS DE FORMA EFECTIVA Y CONCRETA
#ESTE PROCESO INICIA CON EL PLANTEAMIENTO DEL PROBLEMA DEL CUAL DEPENDERA LA RECOLECCION DE INFORMACION, DISEÑAR EL METODO APROPIADO DE RECOLECCION DE INFORMACION
#IDENTIFICAR LOS PROBLEMAS O FUENTES DE ERROR EN EL METODO DE RECOLECCION Y FINALMENTE LA RECOLECCION DE INFORMACION
#ES DE SUMA IMPORTANCIA TENER UN PLAN DE TRABAJO EN EL QUE SE DESCRIBAN DE MANERA PRECISA LAS TECNICAS A UTILIZAR PARA LLEVAR A CABO EL ANALISIS, YA QUE DE LOS CONTRARIO SE PUEDEN OBTENER CONCLUSIONES ERRONEAS.

#CONCEPTOS BASICOS DEL DISEÑO DE EXPERIMENTOS
#VARIABLE(S) INDEPENDIENTE(S):LA O LAS VARIABLES QUE SE ESPERA INCIDAN EN EL COMPORTAMIENTO DE LA VARIABLE DE INTERES.
#VARIABLE DEPENDIENTE:LA VARIABLE DE INTERES, QUE SE ESPERA SEA AFECTADA POR LAS VARIACIONES EN LA(S) VARIABLE(S) INDEPENDIENTE(S)
#HIPOTESIS:ES UNA SUPOSICION QUE BUSCA EXPLICAR EL COMPORTAMIENTO DE UN FENOMENO.
#TAMAÑO DE LA MUESTRA:ES EL NUMERO DE OBSERVACIONES EXPERIMENTALES QUE SE INCLUIRAN EN EL ANALISIS
#DISTORSIONADOR:VARIABLE EXOGENA AL ANALISIS QUE INCIDE EN LA RELACION ENTRE LA(S) VARIABLE(S) INDEPENDIENTE(S) Y DEPENDIENTE, CUYA EXCLUSION PRODUCE CONCLUSIONES ERRONEAS
#VARIABLE DE CONTROL:VARIABLE SOBRE LA CUAL EL INVESTIGADOR TIENE INCIDENCIA Y LE PERMITE REDUCIR EN CIERTO GRADO LOS EFECTOS ADVERSOS ASOCIADOS AL DISTORSIONADOR



