
                      ## LECCION 1
                # CONTROL DE CAMBIOS EN R

# PERMITE RECONOCER QUE MODIFICACIONES SE HAN RELIZADO A UN CODIGO, CUANDO Y QUIEN LAS REALIZO
# AL REALIZAR UNA MODIFICACIÓN EL CONTROL DE CAMBIOS GUARDA UNA CAPTURA DE LA VERSIÓN ORIGINAL DEL CODIGO
# PEMITIENDO REGRESAR A LA VERSION ORIGINAL EN CASO DE SER NECESARIO

# EXISTEN DISTINTOS SISTEMAS QUE PERMITEN REGISTRAR EL CONTROL DE CAMBIOS EN UN CODIGO.
# UNO DE ESTOS SISTEMAS ES GIT.

# VENTAJAS DE UTILIZAR EL CONTROL DE CAMBIOS

# 1.PERMITE INCLUIR EN UN SOLO ARCHIVO TODAS LAS REVISIONES, ELIMINANDO LA NECESIDAD DE CONTAR CON MULTIPLES VERSIONES DE UN DOCUMENTO.
# 2.ELIMINA LOS ERRORES ASOCIADOS A LA UTILIZACION DE UNA VERSION EQUIVOCADA DEL DOCUMENTO.
# 3.PERMITE QUE MULTIPLES PERSONAS TRABAJEN EN UN MISMO DOCUMENT, UNIENDO LAS VERSIONES DEL DOCUMENTO ELABORADAS POR CADA PERSONA EN UN SOLO DOCUMENTO.
# 4.PERMITE GUARDAR COPIAS CON LA VERSION MAS ACTUALIZADA DE MANERA LOCAL, PARAR SU MODIFICACION Y POSTERIOR ENVIO A UN REPOSITORIO COMUN.
# 5.GUARDA UN REGISTRO DE TODOS LOS CAMBIOS REALIZADOS A UN DOCUMENTO, PERMITIENDO REGRESAR A VERSIONES ANTERIORES EN CASO DE ERRORES O CORRECCIONES.

#GIT VS GITHUB

#GIT ES UN SOFTWARE LOCAL ENCARGADO DE REGISTRAR EL CONTROL DE CAMBIOS.
#GITHUB ES UN REPOSITORIO EN LINEA EN EL CUAL SE GUARDAN LOS ARCHIVOS Y LOS CAMBIOS REALIZADOS EN ESTOS ARCHIVOS.

# VOCABULARIO DE GITHUB

#REPOSITORY: ES LA CARPETA EN LA CUAL SE ALMACENAN LOS ARCHIVOS DE TRABAJO Y EL HISTORIAL DE CAMBIOS.
#COMMIT: ES EL REGISTRO DE CADA CAMBIO REALIZADO AL ARCHIVO. AL REALIZAR CAMBIOS A UN ARCHIVO SE DEBE AGREGAR UNA NOTA QUE DESCRIBA LOS CAMBIOS REALIZADOS Y SU FINALIDAD.
#PUSH: ENVIA AL REPOSOTORIO LOS CAMBIOS REALIZADOS EN EL ARCHIVO.
#PULL: DESCARGA DEL REPOSITORIO EL ARCHIVO MAS RECIENTE
#STAGING: EN CASO DE CONTAR CON MAS DE UNA VERSION MODIFICADA DEL ARCHIVO, PARA LA CUALES SE QUIERE INDICAR EXPLICITAMENTE LOS CAMBIOS DE UNA A OTRA VERSION SE DEBEN SUBIR LOS ARCHIVOS EN FORMA ESCALONADA ACOMPAÑADOS DE LAS DESCRIPCIÓN CORRESPONDIENTE.
#BRANCH: SE DENOMINA DE ESTA FORMA A LA SITUACION EN LA CUAL SE CUENTA CON DOS COPIAS DE UN ARCHIVO PARA TRABAJAR DE FORMA SIMULTANEA FUERA DEL REPOSITORIO.
#MERGE: ES LA ACCION DE COMBINAR DOS O MAS VERSIONES DE UN ARCHIVO
#CONFLICT: SE PRESENTA CUANDO DOS O MAS USUARIOS REALIZAN MODIFICACIONES A UN ARCHIVO AL MISMO TIEMPO. EN ESTA SITUACION GIT ES INCAPAZ DE IDENTIFICAR EL ORDEN PARA UNIRLOS POR LO CUAL SE ACTIVA LA OPCION DE UNION MANUAL.
#CLONE: ACCION POR LA CUAL SE REALIZA UNA COPIA DE UN REPOSITORIO.
#FORK: PERMITE GUARDAR UNA COPIA PERSONAL DE UN REPOSITORIO EN LA CUAL LOS CAMBIOS REALIZADOS A UN ARCHIVO NO SE REFLEJAN EN EL REPOSITORIO COMPARTIDO. 

# UTILIZANDO REPOSITORIOS

#SE ACONSEJA UTILIZAR UN REPOSITORIO PARA CADA PROYECTO E INCLUIR UN ARCHIVO DE TEXTO CON UNA DESCRIPCION BREVE DEL PROYECTO

# PASOS PARA TRABAJAR CON CONTROL DE CAMBIOS

# 1.CREAR UN ARCHIVO.
# 2.GUARDAR EL ARCHIVO(EN EL DISCO LOCAL).
# 3.REGISTRAR LOS CAMBIOS (COMMIT)
# 4.GUARDAR EL ARCHIVO EN EL REPOSITORIO DE GITHUB (PULL).

###############################################################################################################################################################################################################################################################################

                        ## LECCION 2
                  # VINCULAR RSTUDIO Y GITHUB

# PASOS PARA VINCULAR RSTUDIO Y GITH:

#1.EN RSTUDIO IR A TOOLS->GLOBAL OPTIONS->GIT/SVN
#2.VERIFICAR QUE LA DIRECCION EN QUE SE ENCUENTRA RSTUDIO CONCUERDE CON LA SEÑALADA EN LA VENTANA DE OPCIONES Y SELECCIONAR ACEPTAR

#PASOS PARA VINCULAR RSTUDIO Y GITHUB
#1.EN RSTUDIO IR A TOOLS->GLOBAL OPTIONS->GIT/SVN
#2.SELECCIONAR LA OPCION "CREATE RSA KEY" Y SELECCIONAR CERRAR AL FINALIZAR.
#3.SELECCIONAR LA OPCION "VIEW PUBLIC KEY" Y COPIAR EL CODIGO DE ESTA VENTANA, UNA VEZ COPIADO CERRAR LA VENTANA.
#4.INICIAR SESION EN GITHUB->IR A "SETTINGS"-> "SSH AND GPG KEYS"-> "NEW SSH KEY"-> PEGAR EL CODIGO COPIADO PREVIAMENTE, ASIGNAR UN NOMBRE Y ACEPTAR

#AL COMPLETAR LOS PASOS ANTERIORES GIT/GITHUB Y RSTUDIO ESTARÁN VINCULADOS.

#CREAR UN REPOSITORIO Y EDITARLO EN RSTUDIO

#PASOS PARA CREAR EL REPOSITORIO:

#1.EN GITHUB-> SELECCIONAR NUEVO REPOSITORIO-> ASIGNAR UN NOMBRE Y DESCRIPCION AL NUEVO REPOSITORIO-> SELECCIONAR CREAR Y COPIAR LA DIRECCION DEL REPOSITORIO.
#2.EN RSTUDIO-> "FILE"->"NEW PROJECT"-> "VERSION CONTROL(TERCERA OPCION)"->SELECCIONAR GIT->PEGAR LA DIRECCION COPIADA PREVIAMENTE Y ELEGIR LA CARPETA EN QUE SE GUARDARA->SELECCIONAR "CREATE PROJECT".
#3.SE ABRIRA UN NUEVO PROYECTO Y UNA NUEVA SESION.
#4.CREAR UN NUEVO SCRIPT Y PEGAR EL SIGUIENTE CODIGO:

print("This file was created within Rstudio")

print("And now it lives on GitHub")

#5.GUARDAR EL ARCHIVO.
#6.EN LA VENTANA SUPERIOR DERECHA BUSCAR LA OPCION "GIT"->SELECCIONAR LA CASILLA "STAGED" A UN COSTADO DEL SCRIPT CREADO->SELECCIONAR "COMMIT"->CERRAR LA VENTANA
#7.A CONTINUACION SE DEBE ENVIAR EL ARCHIVO ACTUALIZADO CON CONTROL DE CAMBIOS AL REPOSITORIO DE GITHUB->SELECCIONAR "PUSH"-> EN GITHUB VERIFICAR QUE EL ARCHIVO SE HAYA ACTUALIZADO.

###############################################################################################################################################################################################################################################################################

                            ## LECCION 3
              # VINCULAR PROYECTOS EXISTENTES A GITHUB

#PASOS PARA VINCULAR UN PROYECTO EXISTENTE A GITHUB

#1.SELECCIONAR "FILE"-> "NEW PROJECT"-> "NEW DIRECTORY"-> "NEW PROJECT", NOMBRAR EL PROYECTO-> NO MARCAR LA CASILLA "CREATE A GIT REPOSITORY".
#2.ABRIR GITBASH Y NAVEGAR EN EL DIRECTORIO HASTA ENCONTRAR LA CARPETA QUE CONTIENE EL ARCHIVO UTILIZANDO LOS SIGUIENTES COMANDOS:
# pwd -> cd /Users/scorp\OneDrive\ESCRITORIO/RES

##NOTAS SOBRE GITBASH

## A)PWD: PRINT WORKING DIRECTORY 
## B)CD: CHANGE DIRECTORY
##    B1)TRUCO: PARA FIJAR RUTAS DE MANERA SENCILLA ESCRIBIR EL COMANDO CD, POSTERIORMENTE ESCRIBIR LAS PRIMERAS LETRAS DEL NOMBRE DE LA CARPETA O ARCHIVO QUE REFERIRA LA RUTA Y APRETAR TAB.
##        DE ESTA FORMA GIT AUTOCOMPLETA LA RUTA SIN ERRORES.
##    B2)TRUCO: PARA REGRESAR UN NIVEL EN LA RUTA INGRESAR EL COMANDO CD ..
##    B3)TRUCO: PARA REGRESAR DOS NIVELES EN LA RUTA INGRESAR EL COMANDO CD ../..
##    B4)TRUCO: PARA BORRAR LA DIRECCION A LA DERECHA DEL CURSOR OPRIMIR CTRL+K
##    B5)TRUCO: PARA BORRAR LA DIRECCION A LA IZQUIERDA DEL CURSOR OPRIMIR CTRL+U
## C)MKDIR(NAME): MAKE DIRECTORY
## D)LS:LISTA LOS ARCHIVOS Y CARPETAS EN ESA DIRECCION
## E)LS -L:LISTA LOS ARCHIVOS Y CARPETAS EN ESA DIRECCION (ORDENADO EN COLUMNAS)
## F)LS -L (LETRA)*:LISTA LOS ARCHIVOS Y CARPETAS EN ESA DIRECCION QUE INICIAN CON ESA LETRA 
## G)LS -A (LETRA)*:LISTA TODOS LOS ARCHIVOS Y CARPETAS EN ESA DIRECCION INCLUSO ARCHIVOS OCULTOS
## H)CTRL+L: LIMPIA LA PANTALLA, PERO CONSERVA EL COMANDO QUE SE ESTE ESCRIBIENDO EN ESE MOMENTO
## I)CLEAR: LIMPIA LA PANTALLA POR COMPLETO
## J)PARA INDICAR UNA RUTA DE MANERA RAPIDA: ABRIR EL EXPLORADOR DE ARCHIVOS->SELECCIONAR LA CARPETA DE TRABAJO DESEADA CON CLICK DERECHO Y ELEGIR LA OPCION "GIT BASH HERE"

#3.UNA VEZ EN EL DIRECTORIO CORRECTO INGRESAR LOS COMANDOS:
##    GIT INIT: PERMITE INICIALIZAR ESTE DIRECTORIO EN EL REPOSITORIO
##    GIT ADD .: AGREGA LOS ARCHIVOS DE LA RUTA LOCAL AL REPOSITORIO
##    GIT COMMIT -M "INITIAL COMMIT": REGISTRA LOS CAMBIOS REALIZADOS

## LOS PASOS ANTERIORES HAN PERMITIDO CREAR UN PROYECTO DE RSTUDIO Y AHORA DEBE LIGARSE A LA VERSION EN CONTROL DE CAMBIOS

#4.IR A GITHUB Y CREAR UN NUEVO REPOSITORIO(DEBE TENER EL MISMO NOMBRE QUE EL PROYECTO DE R CREADO PREVIAMENTE Y NO SE DEBE INICIAR EL ARCHIVO README, .GITIGNORE O LICENSE)
#5.COPIAR EL CODIGO INCLUIDO EN LA SECCION TITULADA "…or push an existing repository from the command line" Y PEGARLO EN GIT BASH

## REALIZADOS LOS PASOS ANTERIORES YA SE SINCRONIZO EL NUEVO REPOSITORIO CON EL PROYECTO, POR LO QUE AL ABRIR DE NUEVA CUENTA EL PROYECTO YA ESTARA HABILITADA LA OPCION DE GIT EN
## LA VENTANA SUPERIOR DERECHA.

                  ## CLONAR UN REPOSITORIO EXISTENTE EN GITHUB

#PASOS PARA CREAR EL REPOSITORIO:

#1.EN RSTUDIO-> "FILE"->"NEW PROJECT"-> "VERSION CONTROL(TERCERA OPCION)"->SELECCIONAR GIT->PEGAR LA DIRECCION DEL REPOSITORIO QUE SE DESEA CLONAR Y ELEGIR LA CARPETA EN QUE SE GUARDARA->SELECCIONAR "CREATE PROJECT".
#2.SE ABRIRA UN NUEVO PROYECTO Y UNA NUEVA SESION.
#3.CREAR UN NUEVO SCRIPT Y PEGAR EL SIGUIENTE CODIGO:

print("This file was created within Rstudio")

print("And now it lives on GitHub")

#5.GUARDAR EL ARCHIVO.
#6.EN LA VENTANA SUPERIOR DERECHA BUSCAR LA OPCION "GIT"->SELECCIONAR LA CASILLA "STAGED" A UN COSTADO DEL SCRIPT CREADO->SELECCIONAR "COMMIT"->CERRAR LA VENTANA
#7.A CONTINUACION SE DEBE ENVIAR EL ARCHIVO ACTUALIZADO CON CONTROL DE CAMBIOS AL REPOSITORIO DE GITHUB->SELECCIONAR "PUSH"-> EN GITHUB VERIFICAR QUE EL ARCHIVO SE HAYA ACTUALIZADO.


