
                      ## LECCION 1
                # CONTROL DE CAMBIOS EN R

# PERMITE RECONOCER QUE MODIFICACIONES SE HAN RELIZADO A UN CODIGO, CUANDO Y QUIEN LAS REALIZO
# AL REALIZAR UNA MODIFICACIÓN EL CONTROL DE CAMBIOS GUARDA UNA CAPTURA DE LA VERSIÓN ORIGINAL DEL CODIGO
# PEMITIENDO REGRESAR A LA VERSION ORIGINAL EN CASO DE SER NECESARIO

# EXISTEN DISTINTOS SISTEMAS QUE PERMITEN REGISTRAR EL CONTROL DE CAMBIOS EN UN CODIGO.
# UNO DE ESTOS SISTEMAS ES GIT.

# VENTAJAS DE UTILIZAR EL CONTROL DE CAMBIOS

# 1.PERMITE INCLUIR EN UN SOLO ARCHIVO TODAS LAS REVISIONES, ELIMINANDO LA NECESIDAD DE CONTAR CON MULTIPLES VERSIONES DE UN DOCUMENTO.
# 2.ELIMINA LOS ERRORES ASOCIADOS A LA UTILIZACION DE UNA VERSION EQUIVOCADA DEL DOCUMENTO.
# 3.PERMITE QUE MULTIPLES PERSONAS TRABAJEN EN UN MISMO DOCUMENT, UNIENDO LAS VERSIONES DEL DOCUMENTO ELABORADAS POR CADA PERSONA EN UN SOLO DOCUMENTO.
# 4.PERMITE GUARDAR COPIAS CON LA VERSION MAS ACTUALIZADA DE MANERA LOCAL, PARAR SU MODIFICACION Y POSTERIOR ENVIO A UN REPOSITORIO COMUN.
# 5.GUARDA UN REGISTRO DE TODOS LOS CAMBIOS REALIZADOS A UN DOCUMENTO, PERMITIENDO REGRESAR A VERSIONES ANTERIORES EN CASO DE ERRORES O CORRECCIONES.

#GIT VS GITHUB

#GIT ES UN SOFTWARE LOCAL ENCARGADO DE REGISTRAR EL CONTROL DE CAMBIOS.
#GITHUB ES UN REPOSITORIO EN LINEA EN EL CUAL SE GUARDAN LOS ARCHIVOS Y LOS CAMBIOS REALIZADOS EN ESTOS ARCHIVOS.

# VOCABULARIO DE GITHUB

#REPOSITORY: ES LA CARPETA EN LA CUAL SE ALMACENAN LOS ARCHIVOS DE TRABAJO Y EL HISTORIAL DE CAMBIOS.
#COMMIT: ES EL REGISTRO DE CADA CAMBIO REALIZADO AL ARCHIVO. AL REALIZAR CAMBIOS A UN ARCHIVO SE DEBE AGREGAR UNA NOTA QUE DESCRIBA LOS CAMBIOS REALIZADOS Y SU FINALIDAD.
#PUSH: ENVIA AL REPOSOTORIO LOS CAMBIOS REALIZADOS EN EL ARCHIVO.
#PULL: DESCARGA DEL REPOSITORIO EL ARCHIVO MAS RECIENTE
#STAGING: EN CASO DE CONTAR CON MAS DE UNA VERSION MODIFICADA DEL ARCHIVO, PARA LA CUALES SE QUIERE INDICAR EXPLICITAMENTE LOS CAMBIOS DE UNA A OTRA VERSION SE DEBEN SUBIR LOS ARCHIVOS EN FORMA ESCALONADA ACOMPAÑADOS DE LAS DESCRIPCIÓN CORRESPONDIENTE.
#BRANCH: SE DENOMINA DE ESTA FORMA A LA SITUACION EN LA CUAL SE CUENTA CON DOS COPIAS DE UN ARCHIVO PARA TRABAJAR DE FORMA SIMULTANEA FUERA DEL REPOSITORIO.
#MERGE: ES LA ACCION DE COMBINAR DOS O MAS VERSIONES DE UN ARCHIVO
#CONFLICT: SE PRESENTA CUANDO DOS O MAS USUARIOS REALIZAN MODIFICACIONES A UN ARCHIVO AL MISMO TIEMPO. EN ESTA SITUACION GIT ES INCAPAZ DE IDENTIFICAR EL ORDEN PARA UNIRLOS POR LO CUAL SE ACTIVA LA OPCION DE UNION MANUAL.
#CLONE: ACCION POR LA CUAL SE REALIZA UNA COPIA DE UN REPOSITORIO.
#FORK: PERMITE GUARDAR UNA COPIA PERSONAL DE UN REPOSITORIO EN LA CUAL LOS CAMBIOS REALIZADOS A UN ARCHIVO NO SE REFLEJAN EN EL REPOSITORIO COMPARTIDO. 

# UTILIZANDO REPOSITORIOS

#SE ACONSEJA UTILIZAR UN REPOSITORIO PARA CADA PROYECTO E INCLUIR UN ARCHIVO DE TEXTO CON UNA DESCRIPCION BREVE DEL PROYECTO

# PASOS PARA TRABAJAR CON CONTROL DE CAMBIOS

# 1.CREAR UN ARCHIVO.
# 2.GUARDAR EL ARCHIVO(EN EL DISCO LOCAL).
# 3.REGISTRAR LOS CAMBIOS (COMMIT)
# 4.GUARDAR EL ARCHIVO EN EL REPOSITORIO DE GITHUB (PULL).

###############################################################################################################################################################################################################################################################################

                        ## LECCION 2
                  # VINCULAR RSTUDIO Y GITHUB

# PASOS PARA VINCULAR RSTUDIO Y GITH:

#1.EN RSTUDIO IR A TOOLS->GLOBAL OPTIONS->GIT/SVN
#2.VERIFICAR QUE LA DIRECCION EN QUE SE ENCUENTRA RSTUDIO CONCUERDE CON LA SEÑALADA EN LA VENTANA DE OPCIONES Y SELECCIONAR ACEPTAR

#PASOS PARA VINCULAR RSTUDIO Y GITHUB
#1.EN RSTUDIO IR A TOOLS->GLOBAL OPTIONS->GIT/SVN
#2.SELECCIONAR LA OPCION "CREATE RSA KEY" Y SELECCIONAR CERRAR AL FINALIZAR.
#3.SELECCIONAR LA OPCION "VIEW PUBLIC KEY" Y COPIAR EL CODIGO DE ESTA VENTANA, UNA VEZ COPIADO CERRAR LA VENTANA.
#4.INICIAR SESION EN GITHUB->IR A "SETTINGS"-> "SSH AND GPG KEYS"-> "NEW SSH KEY"-> PEGAR EL CODIGO COPIADO PREVIAMENTE, ASIGNAR UN NOMBRE Y ACEPTAR

#AL COMPLETAR LOS PASOS ANTERIORES GIT/GITHUB Y RSTUDIO ESTARÁN VINCULADOS.

#CREAR UN REPOSITORIO Y EDITARLO EN RSTUDIO

#PASOS PARA CREAR EL REPOSITORIO:

#1.EN GITHUB-> SELECCIONAR NUEVO REPOSITORIO-> ASIGNAR UN NOMBRE Y DESCRIPCION AL NUEVO REPOSITORIO-> SELECCIONAR CREAR Y COPIAR LA DIRECCION DEL REPOSITORIO.
#2.EN RSTUDIO-> "FILE"->"NEW PROJECT"-> "VERSION CONTROL(TERCERA OPCION)"->SELECCIONAR GIT->PEGAR LA DIRECCION COPIADA PREVIAMENTE Y ELEGIR LA CARPETA EN QUE SE GUARDARA->SELECCIONAR "CREATE PROJECT".
#3.SE ABRIRA UN NUEVO PROYECTO Y UNA NUEVA SESION.
#4.CREAR UN NUEVO SCRIPT Y PEGAR EL SIGUIENTE CODIGO:

print("This file was created within Rstudio")

print("And now it lives on GitHub")

#5.GUARDAR EL ARCHIVO.
